In [38]:
# Basic Usage

In [3]:
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()

## tf.stack

In [31]:
w = [[1,2], [3,4]]
x = [[5,6], [7,8]]
y = [[9,10], [11,12]]
z = [[13,14], [15,16]]


a = tf.constant(w)
b = tf.constant(x)
c = tf.constant(y)
d = tf.constant(z)

print('a:\n', a.eval(),'\n')
print('b:\n', b.eval(), '\n')
print('c:\n', c.eval(), '\n')
print('d:\n', c.eval(), '\n')

batch1 = tf.stack([a, b, c, d], axis=0)
batch2 = tf.stack([d, c, b, a], axis=0)

print('batch1 shape:', batch1.shape)
print(batch1.eval(), '\n')

print('batch2 shape:', batch2.shape)
print(batch2.eval(), '\n')

a:
 [[1 2]
 [3 4]] 

b:
 [[5 6]
 [7 8]] 

c:
 [[ 9 10]
 [11 12]] 

d:
 [[ 9 10]
 [11 12]] 

batch1 shape: (4, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]] 

batch2 shape: (4, 2, 2)
[[[13 14]
  [15 16]]

 [[ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]]

 [[ 1  2]
  [ 3  4]]] 



### slicing and indexing

In [37]:
batch1_odd  = batch1[::2]
batch1_even = batch1[1::2]
batch2_odd  = batch2[::2]
batch2_even = batch2[1::2]

print('batch1_odd shape:', batch1_odd.shape)
print('batch1_even shape:', batch1_even.shape)
print('batch2_odd shape:', batch2_odd.shape)
print('batch2_even shape:', batch2_even.shape)

print()
print('batch1_odd:\n', batch1_odd.eval(), '\n')
print('batch1_even:\n', batch1_even.eval(), '\n')
print('batch2_odd:\n', batch2_odd.eval(), '\n')
print('batch2_even:\n', batch2_even.eval(), '\n')

batch1_odd shape: (2, 2, 2)
batch1_even shape: (2, 2, 2)
batch2_odd shape: (2, 2, 2)
batch2_even shape: (2, 2, 2)

batch1_odd:
 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [11 12]]] 

batch1_even:
 [[[ 5  6]
  [ 7  8]]

 [[13 14]
  [15 16]]] 

batch2_odd:
 [[[13 14]
  [15 16]]

 [[ 5  6]
  [ 7  8]]] 

batch2_even:
 [[[ 9 10]
  [11 12]]

 [[ 1  2]
  [ 3  4]]] 



## tf.einsum
#### maxtrix multiplication for batch: $[C]_{i,j,k} = \sum_{s} [A]_{i,j,s} \bullet [B]_{i,s,k}$  or C(i,:,:) = tf.matmul(A(i,:,:) , B(i,:,:))

In [30]:
mul0 = tf.matmul(batch1[0,:,:], batch2[0,:,:])
mul1 = tf.matmul(batch1[1,:,:], batch2[1,:,:])
mul2 = tf.matmul(batch1[2,:,:], batch2[2,:,:])

bmul = tf.einsum('ijs,isk->ijk', batch1, batch2)

print('mu0:\n', mul0.eval(), '\n')
print('mu1:\n', mul1.eval(), '\n')
print('mu2:\n', mul2.eval(), '\n')

print('bmul shape:', bmul.shape)
print(bmul.eval())

mu0:
 [[31 34]
 [71 78]] 

mu1:
 [[ 67  78]
 [ 91 106]] 

mu2:
 [[39 58]
 [47 70]] 

bmul shape: (3, 2, 2)
[[[ 31  34]
  [ 71  78]]

 [[ 67  78]
  [ 91 106]]

 [[ 39  58]
  [ 47  70]]]
